---
- name: Check if logstash is installed
  command: bash -c "service --status-all | grep logstash"
  register: logstash_installed
  ignore_errors: True
  tags:
    - logstash_setup

- name: Install logstash
  apt: name=logstash state=present force=yes
  when: logstash_installed|failed
  tags:
    - logstash_setup

- name: Create logstash etc directory
  file: path=/etc/logstash/conf.d state=directory
  tags:
    - logstash_dir

- name: Add heroku logstash conf file
  template: src=heroku.conf dest=/etc/logstash/conf.d/heroku.conf
  tags:
    - conf_file

- name: Start logstash
  service: name=logstash state=started enabled=yes
  tags:
    - logstash_setup
