---
- name: Check if logstash is installed
  command: bash -c "service --status-all | grep logstash"
  register: logstash_installed
  ignore_errors: True

- name: Install logstash
  apt: name=logstash state=present force=yes
  when: logstash_installed|failed

- name: Start logstash
  service: name=logstash state=started enabled=yes
