---
- name: Check if nginx is installed
  command: bash -c "service --status-all | grep nginx"
  register: nginx_installed
  ignore_errors: True
  tags:
    - nginx_setup

- name: Install nginx
  apt: name=nginx state=present force=yes
  when: nginx_installed|failed
  notify:
    - start nginx
  tags:
    - nginx_setup

- name: Create ssl directory
  file: path=/etc/nginx/ssl state=directory
  tags:
    - ssl_dir

- name: Create a self-signed SSL certificate
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN"=${ansible_fqdn} -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt
  notify:
    - restart nginx
  tags:
    - ssl_cert

- name: Check if apache2_utils is installed
  command: bash -c "dpkg --get-selections | grep apache2-utils"
  register: apache2_utils_installed
  ignore_errors: True
  tags:
    - apache2_utils_setup

- name: Install apache2-utils
  apt: name=apache2-utils state=present force=yes
  when: apache2_utils_installed|failed
  tags:
    - apache2_utils_setup

- name: Check if python passlib is installed
  command: bash -c "dpkg --get-selections | grep python-passlib"
  register: passlib_installed
  ignore_errors: True
  tags:
    - passlib_setup

- name: Install python passlib
  apt: name=python-passlib state=present force=yes
  when: passlib_installed|failed
  tags:
    - passlib_setup

- name: Create kibana.htpassword
  htpasswd: path=/etc/nginx/conf.d/kibana.htpasswd name={{username}} password={{password}} crypt_scheme=md5_crypt
  tags:
    - kibana.htpassword

- name: Create kibana-write.htpassword
  htpasswd: path=/etc/nginx/conf.d/kibana-write.htpasswd name={{username}} password={{password}} crypt_scheme=md5_crypt
  tags:
    - kibanawrite.htpassword

- name: Copy kibana nginx file
  template: src=nginx_kibana dest=/etc/nginx/sites-enabled/kibana
  tags:
    - kibana_sites_available
  notify:
    - restart nginx
