---
- hosts: all
  user: vagrant
  become: yes
  become_method: sudo
  vars_files:
    - "/Users/kosyanyanwu/workspace/vars/elk_secure.yml"
  roles:
    - { role: elasticsearch, tags: 'elasticsearch_setup' }
    - { role: kibana, tags: 'kibana_setup' }
    - logstash
    - nginx
